export enum AuditAction {
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  REQUEST_CREATED = 'REQUEST_CREATED',
  REQUEST_APPROVED = 'REQUEST_APPROVED',
  REQUEST_REJECTED = 'REQUEST_REJECTED',
  REQUEST_CHANGES_REQUESTED = 'REQUEST_CHANGES_REQUESTED',
  REQUEST_RESUBMITTED = 'REQUEST_RESUBMITTED',
  REQUEST_TAKEN_IN_CHARGE = 'REQUEST_TAKEN_IN_CHARGE',
  REQUEST_PROCESSED = 'REQUEST_PROCESSED',
  REQUEST_REJECTED_TECHNICAL = 'REQUEST_REJECTED_TECHNICAL',
  REQUEST_CLOSED = 'REQUEST_CLOSED',
  REQUEST_EXPIRED = 'REQUEST_EXPIRED',
  REQUEST_PDF_EXPORTED = 'REQUEST_PDF_EXPORTED',
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_ACTIVATED = 'USER_ACTIVATED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
  USER_DELETED = 'USER_DELETED',
  ROLE_CHANGED = 'ROLE_CHANGED',
  DEPARTMENT_CREATED = 'DEPARTMENT_CREATED',
  DEPARTMENT_UPDATED = 'DEPARTMENT_UPDATED',
  DEPARTMENT_DELETED = 'DEPARTMENT_DELETED',
  SERVICE_CREATED = 'SERVICE_CREATED',
  SERVICE_UPDATED = 'SERVICE_UPDATED',
  SERVICE_DELETED = 'SERVICE_DELETED',
  // --- Cycle de vie d'un compte (création par invitation) ---
  /** Compte créé par une personne habilitée, lien d'activation généré */
  USER_INVITED = 'USER_INVITED',
  /** Nouveau lien d'activation généré (l'ancien est invalidé) */
  USER_INVITATION_RESENT = 'USER_INVITATION_RESENT',
  /** L'employé a défini son mot de passe via le lien : compte utilisable */
  ACCOUNT_ACTIVATED = 'ACCOUNT_ACTIVATED',
  /** Lien d'activation invalide, expiré ou déjà utilisé */
  ACTIVATION_FAILED = 'ACTIVATION_FAILED',
  /** Changement de mot de passe imposé à la prochaine connexion */
  PASSWORD_RESET_ENFORCED = 'PASSWORD_RESET_ENFORCED',
  // --- Gestion des formulaires (super administrateur) ---
  FORM_UPDATED = 'FORM_UPDATED',
  FORM_ACTIVATED = 'FORM_ACTIVATED',
  FORM_DEACTIVATED = 'FORM_DEACTIVATED',
  FORM_RESET = 'FORM_RESET',
  // --- Assistance à la rédaction (IA) ---
  /** Un employé a fait reformuler sa justification */
  AI_JUSTIFICATION_IMPROVED = 'AI_JUSTIFICATION_IMPROVED',
  /** Un validateur a demandé la synthèse d'une justification */
  AI_JUSTIFICATION_SUMMARIZED = 'AI_JUSTIFICATION_SUMMARIZED',
  // --- Messagerie interne (contenu non journalisé, seul l'échange est tracé) ---
  MESSAGE_SENT = 'MESSAGE_SENT',
  THREAD_RESOLVED = 'THREAD_RESOLVED',
  THREAD_REOPENED = 'THREAD_REOPENED',
}
